name: Deploy

on:
  pull_request:
    types: [closed]
    branches:
      - master

jobs:
  build:
    name: Deploy
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged
    steps:
      - uses: actions/checkout@v1
      - uses: borales/actions-yarn@v2.0.0
        with:
          cmd: install 
      - uses: borales/actions-yarn@v2.0.0
        with:
          cmd: build 

      - name: Go into dist folder 
        run: |
            sudo sh -c "echo 'docs.sigmie.com' > docs/.vuepress/dist/CNAME"

      - name: wget changelog.md
        uses: wei/wget@v1
        with:
          args: -O docs/sigmie/changelog.md https://raw.githubusercontent.com/sigmie/sigmie/master/CHANGELOG.md

      - name: Add to staging area
        run: |
           cd docs/.vuepress/dist
           git config --global user.name 'Nico'
           git config --global user.email 'nico@sigmie.com'
           sudo git init
           sudo git add .
           sudo git commit -m 'deploy'
           git push -f https://${{ secrets.ACCESS_TOKEN }}@github.com/sigmie/docs.sigmie.com.git master



